/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package HungerGames;

import HungerGames.EventsList.BearAttack.BearAttack;
import HungerGames.EventsList.BearAttack.BearAttackCombat;
import HungerGames.EventsList.BearAttack.BearAttackRun;
import HungerGames.EventsList.Event;
import HungerGames.EventsList.FindShelter.FindShelter;
import HungerGames.EventsList.FindShelter.FindShelterCamo;
import HungerGames.EventsList.FindShelter.FindShelterClimb;
import HungerGames.EventsList.FoodCook;
import HungerGames.EventsList.FoodSearch.FoodSearch;
import HungerGames.EventsList.FoodSearch.FoodSearchArchery;
import HungerGames.EventsList.FoodSearch.FoodSearchRunning;
import HungerGames.EventsList.ForestFire.ForestFire;
import HungerGames.EventsList.ForestFire.ForestFireBuilding;
import HungerGames.EventsList.ForestFire.ForestFireRunning;
import HungerGames.EventsList.Sleep;
import HungerGames.EventsList.WaterSearch.WaterSearch;
import HungerGames.EventsList.WaterSearch.WaterSearchClimb;
import HungerGames.EventsList.WolfPack.WolfPack;
import HungerGames.EventsList.WolfPack.WolfPackClimb;
import HungerGames.EventsList.WolfPack.WolfPackCombat;

/**
 *
 * @author chri8160
 */
public class HungerGames extends javax.swing.JFrame {

    /**
     * Creates new form HungerGames
     */
    Tribute[] t = new Tribute[3];
    FoodSearch[] f = new FoodSearch[3];
    FindShelter[] s = new FindShelter[3];
    WaterSearch[] w = new WaterSearch[3];
    FoodCook[] c = new FoodCook[3];
    Sleep[] sl = new Sleep[3];
    BearAttack[] ba = new BearAttack[3];
    BearAttackCombat[] bac = new BearAttackCombat[3];
    BearAttackRun[] bar = new BearAttackRun[3];
    FoodSearchArchery[] fa = new FoodSearchArchery[3];
    FoodSearchRunning[] fr = new FoodSearchRunning[3];
    FindShelterCamo[] fsc = new FindShelterCamo[3];
    FindShelterClimb[] fcl = new FindShelterClimb[3];
    ForestFire[] ff = new ForestFire[3];
    ForestFireBuilding[] ffb = new ForestFireBuilding[3];
    ForestFireRunning[] ffr = new ForestFireRunning[3];
    WaterSearchClimb[] wc = new WaterSearchClimb[3];
    WolfPack[] wp = new WolfPack[3];
    WolfPackClimb[] wpc = new WolfPackClimb[3];
    WolfPackCombat[] wpco = new WolfPackCombat[3];
    int counter = 0;
    boolean gg = false;
    public HungerGames() {
        initComponents();
        btnrestart.setEnabled(false);
        btnrestart.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        txtarea = new javax.swing.JTextArea();
        btnstart = new javax.swing.JButton();
        btnrestart = new javax.swing.JButton();
        lblname1 = new javax.swing.JLabel();
        lblname2 = new javax.swing.JLabel();
        lblname3 = new javax.swing.JLabel();
        lblstatus1 = new javax.swing.JLabel();
        lblstatus2 = new javax.swing.JLabel();
        lblstatus3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtarea.setColumns(20);
        txtarea.setRows(5);
        jScrollPane1.setViewportView(txtarea);

        btnstart.setText("Start");
        btnstart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnstartActionPerformed(evt);
            }
        });

        btnrestart.setText("Restart");
        btnrestart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnrestartActionPerformed(evt);
            }
        });

        lblname1.setText("Tribute1");

        lblname2.setText("Tribute2");

        lblname3.setText("Tribute3");

        lblstatus1.setText("Alive");

        lblstatus2.setText("Alive");

        lblstatus3.setText("Alive");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setText("Tribute                                                         Status");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblname1, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblname2, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblstatus2, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblstatus1, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblname3, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblstatus3, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(btnrestart)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnstart, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(24, 24, 24))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnstart, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnrestart))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblname1)
                    .addComponent(lblstatus1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblname2)
                    .addComponent(lblstatus2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblname3)
                    .addComponent(lblstatus3))
                .addGap(0, 18, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnstartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnstartActionPerformed
        HungerGamesDialogForm form = new HungerGamesDialogForm(this,true);
        form.setVisible(true);
        if(form.getSignal().equals("ok")){
            for (int i = 0; i < 3; i++) {
            t[i] = new Tribute(form.getName(i));
            if(i==0)lblname1.setText(t[i].getName());
            else if(i==1)lblname2.setText(t[i].getName());
            else lblname3.setText(t[i].getName());
            f[i] = new FoodSearch(t[i],this);
            s[i] = new FindShelter(t[i],i);
            w[i] = new WaterSearch(t[i]);
            c[i] = new FoodCook(t[i]);
           sl[i]= new Sleep(t[i]);
           ba[i]= new BearAttack(t[i]);
            bac[i]= new BearAttackCombat(t[i]);
            bar[i]= new BearAttackRun(t[i]);
           fa[i] = new FoodSearchArchery(t[i]);
           fr[i] = new FoodSearchRunning(t[i]);
           fsc[i] = new FindShelterCamo(t[i],i);
           fcl[i] = new FindShelterClimb(t[i],i);
           ff[i] = new ForestFire(t[i]);
           ffb[i] = new ForestFireBuilding(t[i]);
           ffr[i] = new ForestFireRunning(t[i]);
           wc[i] = new WaterSearchClimb(t[i]);
           wp[i] = new WolfPack(t[i]);
           wpc[i] = new WolfPackClimb(t[i]);
           wpco[i] = new WolfPackCombat(t[i]);
            }
            btnrestart.setEnabled(true);
            btnrestart.setVisible(true);
            btnstart.setEnabled(false);
            btnstart.setVisible(false);
            counter = 0;
            while(true){
                for (int i = 0; i < 3; i++) {
                    
                    if(Tribute.amountAlive<=1){
                        txtarea.append("\n" + t[i].getName() + " is the Winner!");
                        gg=true;
                        break;
                    } 
                    if(t[i].isAlive()){
                    if(t[i].health<=0){
                        txtarea.append("\n" + t[i].getName() + " has died");
                        t[i].Kill();
                    }
                    if(t[i].hunger>=100){
                        txtarea.append("\n" + t[i].getName() + " has starved to death");
                        t[i].Kill();
                    }
                    else if(t[i].hunger>80) f[i].Go();
                    else if(counter==4)w[i].Go();
                    else if(counter==9)s[i].Go();
                    else RandomEvent(i);
                    t[i].hunger+=10;
                        System.out.println(t[i].hunger + " and " + t[i].health);
                    }
                }
                if(gg=true)break;
                counter++;
                System.out.println(counter+"");
            }
        }
    }//GEN-LAST:event_btnstartActionPerformed

    private void btnrestartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnrestartActionPerformed
        btnstart.setEnabled(true);
        btnstart.setVisible(true);
        btnrestart.setEnabled(false);
        btnrestart.setVisible(false);
    }//GEN-LAST:event_btnrestartActionPerformed

    /**
     * @param args the command line arguments
     */
    public void RandomEvent(int i){
        int num=(int)(Math.random()*3)+1;
        switch (num) {
            case 3:
                ba[i].Go();
                break;
            case 2:
                wp[i].Go();
                break;
            default:
                ff[i].Go();
                break;
        }
    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HungerGames.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HungerGames.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HungerGames.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HungerGames.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HungerGames().setVisible(true);
            }
        });
    }
    public void printArea(String s){
        txtarea.append("\n" + s);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnrestart;
    private javax.swing.JButton btnstart;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblname1;
    private javax.swing.JLabel lblname2;
    private javax.swing.JLabel lblname3;
    private javax.swing.JLabel lblstatus1;
    private javax.swing.JLabel lblstatus2;
    private javax.swing.JLabel lblstatus3;
    private javax.swing.JTextArea txtarea;
    // End of variables declaration//GEN-END:variables
}
